
server:
  port: 8090

spring:
  data:
    mongodb:
      uri: mongodb+srv://demo:demo@demo.oubqa.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name : customer-service
  main:
   allow:
    circular:
      references: true
