server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:

        - id: coupon-microservice
          uri: http://localhost:8083/
          predicates:
            - Path=/coupon/**
            
        - id: cart-service
          uri: http://localhost:8087/
          predicates:
            - Path=/cart/**
            
        - id: profile-management
          uri: http://localhost:8085/
          predicates:
            - Path=/user/**

  